### ISSUE TITLE
Minor Animation Flub

### ISSUE THREAD

**Issue by KorytheMaril** [Project-M-CC/lyn#1]
When putting Lyn into the PMEX build with Waluigi, something causes her to t-pose on her second jump. I don't exactly know what causes this, and I didn't play around too much to see if any other animation is having trouble. Checking Brawl Box, all of her animations are in check, so it's definitely something within the game itself that causes this to occur.

**Comment by TheSmashBoy** [comment]
It's like the new characters need to adapt to this fairly 'new' build now that we just moved to PMEX format. If there really is a correlation between the leaked characters' inclusion; their based off clones and the characters they fight or are co-existing with that have similar characters or exactly the same characters they are based off in the clone engine (e.g: Ridley and Lyn being clones of Pit); this is gonna be a serious and heavy problem for us. Let's hope that correlation is false and fallacious and get this fixed.

**Comment by KorytheMaril** [comment]
@TheSmashBoy It's at moments like these I wish I knew more on Smash hacking. Bb010g and Pyotr seemed to somehow get these characters to work without the conflicts (Sonic and Knuckles fought just fine). I'd like to look into this further; I've only added Knuckles and Lyn to my build due to the nature of Isaac and Sami, and this visual bug does bother me. Do you know how these clones were made without their effects being transferred to Subspace enemies?

**Comment by TheSmashBoy** [comment]
@KorytheMaril I feel you, man. 

 I just ported Isaac now and was a success, at least in practice. It's still...bleh. I just won a match and his "have no sympathy from me" pose has TOon Link's pig appear in his face. This never happened before. 

 I have no idea about the Subspace Emissary files. Remember, they were clone engine characters, not BEX characters initially, they never came with their SE files except their Spy files. Nonetheless, I think you can give them one by copying some already existing file and just renaming them properly (FitCharacterDark and FitCharacterFake).

**Comment by TheSmashBoy** [comment]
@KorytheMaril I think bb010g and I figured out what may be causing the bugs: the configtemplates files themselves. Somehow there is a misplaced hex coding or something that may cause the animations to bug. I believe we should start by investigating this error in the FighterConfig template for Lyn.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I'll try opening up the Fighter config in HxD. Perhaps I could find exactly what would need to be edited, but I can't say I'll be so lucky. I'm not that great when it comes to Brawl hacking, so I can't say I'll be that reliable.

**Comment by TheSmashBoy** [comment]
@KorytheMaril I'm not that great of a hacker either, so we are in the same boat. Let's just hope what exactly needs editing and report it.

P.S: Download BrawlEx Config Utility. That program is very useful and may lead us to the problem in another view, in case HxD doesn't lend us a clue. Also, refer to the BrawlEx starter's guide.

**Comment by TheSmashBoy** [comment]
@KorytheMaril It's definitely the config templates. PurpleSquert confirmed it. He has the fixes in which I'm receiving now. You keep finding the problem for double confirmation.

**Comment by KorytheMaril** [comment]
@TheSmashBoy Using the BrawlEX Config tool and checking the fighter.dat, the thing my eye immediately goes to is the AirJumpCount, which is set to 2. That seems to be right, I'd imagine, but I'm noticing the 'CanGlide' being true. Now, this is purely speculation, but going by Knuckle's stuff, that might be the issue. It's most likely that Lyn is trying to load a gliding animation (like Kirby and Jigglypuff, I'm guessing) that isn't there, so it goes to T-Pose. That's just my guess, but let me see if this changes anything if I change it.

**Comment by TheSmashBoy** [comment]
@KorytheMaril Lyn cannot glide. Set that to false.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I did so, and yet it did not fix her t-pose issue. The glide was probably borrowed from Pit, I'm guessing.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I FIXED THE ISSUE: IT'S HER AIRJUMPCOUNT! Set her AirJumpCount to 1.

**Comment by TheSmashBoy** [comment]
@KorytheMaril This may need more investigation. We now know she can't glide but somehow is not enough. I downloaded the Lyn files myself. I'll see what else is odd and I'll report it. Keep searching though.

**Comment by KorytheMaril** [comment]
@TheSmashBoy Would you happen to have a sort of move log for her? The only other concerning things with her fighter.dat right now seem to be her HasRapidJab, her JabCount and her JabFlag.

**Comment by TheSmashBoy** [comment]
@KorytheMaril She only has two possible jabs and they aren't rapid. Don't know about the flags though. I'm going to check her right now, now that I have her files. I'm eliminating Isaac from the build I have to have Lyn checked up.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I guess, just in case, I'd check out the other fighter.dat files so they match up with the character movesets. If you happen to have move logs for the 4 characters, might I ask to study them, so that I can check the fighter.dat files for each?

**Comment by TheSmashBoy** [comment]
@KorytheMaril I just noticed her CanWallJump was set to false when it actually is true. 

As for the log, Lyn is the only wall jumper, Knuckles can only glide. Sami is the only crawler. Also, Isaac does not have a working Final Smash, the rest do: Sami's is basically Snake's, Lyn's is currently Pit's FS.

**Comment by TheSmashBoy** [comment]
That's basically some useful info. I can give you. Also, about the Jab Flags, the Config program says it has an unknown usage, so leave that be.

**Comment by KorytheMaril** [comment]
@TheSmashBoy When you say glide for Knuckles, do you mean his side B? His glide is turned off, but it seems his side B works fine without it. I'm not exactly sure, then, what it means for a character to have a glide.

Sami's stuff should be just fine currently: She's so close to Snake and has so many of his attributes that her Fighter.dat should be fine.

**Comment by KorytheMaril** [comment]
@TheSmashBoy As it turns out, it appears everything for Lyn is working fine now. If her jab only hits twice, then it's just a matter of uploading the files. Consider this problem solved, sir!

**Comment by TheSmashBoy** [comment]
@KorytheMaril Wait, you mean you fixed Lyn? It was the CanWallJump and CanGlide and RapidJab fixes? How'd you do it?

**Comment by KorytheMaril** [comment]
@TheSmashBoy It was all in the fighter.dat files. I used the info you gave me on Lyn: her two jabs, turning off the rapid jab, fixing her AirJumpCount to 1, stuff like that. I'll update the current EX Files shortly.

**Comment by TheSmashBoy** [comment]
I see! Purple and I were correct! Great job Kory! I'll report to bb right away!

**Comment by TheSmashBoy** [comment]
This issue is officially closed!

**Comment by KorytheMaril** [comment]
@TheSmashBoy I'm glad I could help; I'll close the issue once the files are updated, I guess. I have it in a zip folder already, if you want.

**Comment by TheSmashBoy** [comment]
@KorytheMaril Upload them in the GH and I'll have a look at them when I finish with my Lyn. Remember to set them back to their default (FF).

 You were awesome in that, Kory. This is actually very helpful and cuts some some slack and can help us get back on focusing in polishing animations.

**Comment by KorytheMaril** [comment]
@TheSmashBoy ...I must apologize, could I ask what the GH is...? I'm really sorry.

**Comment by TheSmashBoy** [comment]
@KorytheMaril GH=GitHub.

**Comment by TheSmashBoy** [comment]
PR= Pull Request.

**Comment by KorytheMaril** [comment]
@TheSmashBoy Oh boy, I feel like an idiot. I'm sorry.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I don't have access to this project, so I might just upload it to DropBox really quickly and send the link. Is that alright?

**Comment by KorytheMaril** [comment]
@TheSmashBoy Sorry for the spam, but here's the file on Dropbox; I'll delete it as soon as you get it, sir. I apologize for the inconvenience.
https://www.dropbox.com/s/h71rln54wss40yp/lyn-master.zip?dl=0

**Comment by TheSmashBoy** [comment]
@KorytheMaril I got it! Also, to upload files in the GH, go to the fork tab in the Lyn repo. That clones the upstream repo and you can basically upload your fixes there. After that. Ask the Hub to pull request it and bb010g should examine it and merge it with the upstream.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I... Messed up, I think. I am very sorry: I ended up uploading the zip file and the Fighter.dat (in the proper folder, at least...)

**Comment by TheSmashBoy** [comment]
@KorytheMaril You can just upload the Config templates. No need to upload the costumes and animation nor cosmetic portraits. Just the templates are fine.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I'll go in and upload the fighter.dat, at least. I'm so sorry, I've been causing a lot of trouble in little time.

**Comment by TheSmashBoy** [comment]
@KorytheMaril (Chuckles), chill dude. I also have my issues with GH. I still don't even know how to properly PR without simply making simple uploads and not upload my own repo.

**Comment by KorytheMaril** [comment]
@TheSmashBoy Thank you, sir.

**Comment by bb010g** [comment]
@KorytheMaril If you need help making a pull request, just ping me on Matrix and I'll get back as soon as possible to walk you through it. It's a bit strange at first, but it's nothing you can't get the hang of quickly.

**Comment by KorytheMaril** [comment]
@bb010g Ah, thank you, sir. I'll try to set up a Matrix as soon as possible. I apologize for the inconvenience.

**Comment by bb010g** [comment]
I forgot, you probably should have instructions. (I really should just update the main README.) From [here](https://www.reddit.com/r/SSBPMCE/comments/4uvxgl/project_m_community_complete_coming_to_a_pmex/):

> We're over at #pmcc:matrix.org on Matrix. If you want a good client, [Vector](https://vector.im/) does the job well. Just make an account and type that room alias into the directory or just type /join #pmcc:matrix.org into any room's input box.
