### ISSUE TITLE
Cosmetic bug in victory pose

### ISSUE THREAD

**Issue by TheSmashBoy** [Project-M-CC/lyn#2]
SSIA.

When she wins a match, somehow her eyes turn white. PurpleSquert/Rage17 suggests it could be her iris animation being off. Has anyone had this problem?

**Comment by TheSmashBoy** [comment]
Nevermind. I fixed it. You have to check the ?B box in the colors resources when accessing the FighterConfig.dat file of her through the BEx Config Utility program.

**Comment by bb010g** [comment]
Close this when the fixes are pushed.

**Comment by TheSmashBoy** [comment]
@bb010g I actually also fixed (long ago) her eye glitch when she fights Ridley. I can just send you the files to you or here and you sort them out. So I can close this issue since this is already a fixed issue.
