### ISSUE TITLE
[RFC] Lyn Animation Polish by ManlySpirit: Animation and movesets discussion thread-Standardization of ManlySpirit's model for Lyn's gameplay mechanics

### ISSUE THREAD

**Issue by TheSmashBoy** [Project-M-CC/lyn#7]
https://github.com/Project-M-CC/Project-M-CC/issues/305

https://discord.gg/MhRt7rt (my own Lyn Dev Room for Project M Community Completion).

This accompanies his work of his files on her animation, renders and modeling. For those who are integrated in completing Lyn, this is important as well to keep in mind in case in the files he didn't mention a few details the link provides.

# Proposal

For quite some time now, we kept the vanilla build for Lyn, for the purpose to keep with the standards to PM 3.6 work as close as possible, while this is not so bad, we are nonetheless at a guidance disadvantage. This will probably discomfort many who wholeheartedly wish to keep with the PMDT way of developing Lyn, but honestly, there's not a whole lot there. Yeah, there are leaked concept arts, but those available are mere generalities and some little examples that don't really dramatically help develop Lyn to what we want. It's all abstract and ambiguous if you ask me. We need a more concrete model that gets the factors straight, more easily expressed and most importantly, _actually_ guide the animators and PSA'ers to help develop Lyn. The leaked concept arts are great, granted. Just not enough information to help make the development of Lyn more concrete. This is where ManlySpirit comes in. As for those who do recall the earlier post at #305, he makes not just _good_ points, they are excellent and very concrete, detailed and a lot more mechanical. That's key to completion not just with the fours, but with practically every character. Developers know this principle, is absolutely crucial and basic, so we are keeping with this. My proposal? Standardize Manly's model. Period. This is the whole point. Manly hasn't the slightest deviated from what the PMDT 'were going for', and even if we grant it deviates to some parts, so what? Let's be honest, how many of you have been able to concretely state exactly what the PMDT thought about Lyn? The leaked concept arts? How mechanical and detailed is that? The models and animations CC currently has? How do we know for sure? There are a variety of builds for Lyn out there God knows how many have been polished. That, and the fact many of them are unwilling to share a single info. on their development for a variety of reasons none of us have the time to ponder. We need a concrete standard and **now**, I already have my updates for Lyn already patched up, I had Manly play test it for me and he approves of its progress for how solid it is. He even admitted that the U smash is better than what he proposed, same with the up throw. He digs it. This is exactly what we need. Sure, it's from a prototype, but guess what? It _doesn't matter_, does it go with how she is supposed to according to her franchise and nature as a samurai, both style and mechanic? That's all that matters. Below I'll provide further details on what will be taking place with the parameters.

# Parameters and Details

Manly still has some works to be done regarding establishing the theory and parameters to her completion, but this document is enough to be said: 
https://docs.google.com/document/d/180ZVVkyf9QUfRZL4Z8urqrjWFQDCYY7nWKBrevPGvm0/edit?usp=sharing

Some of the moves proposed, particularly his proposed U tilt, and Dair; he felt convinced the one I implemented in the PR was excellent, though like all her moves, they need polish. Same with the nair. And here is where I come in:

The Lyn I will PR will have:
() Kuro Lucina's Nair.
() Proto Lyn's Uair
() Proto Lyn's up smash
() Vanilla Lyn's unused Dair
() Proto Lyn's up throw

Along with some GFX fixes to her nair, relocating the hitboxes of her implemented attacks to fit the animation; relocating the hitboxes of her vantage attack to her katana as well as with her up throw. Numerical details will be provided in a changelog in the Pull Request comment's page, not here.
Manly sees this as excellent. Another thing is I was able to allow interrupt to her Mirror Step, I'll experiment with MS a bit since you can practically infinite spam that move with those commnds in her PSA. So as to go with his fixes. Other comments: He proposes QC inputs, which those will be chaged since PSA button data, to what I know, lacks QC inputs. But it can still be manageable. 

Now onto her animations and models. Manly stated something that will discomfort those who volunteered on working to animate with Lyn, or perhaps put a major stress. Eventually, we will have to change her skeleton. And not necessarily when importing a new model, it's through the course of animating her. How is this a stress? Changing skeleton equals redoing every animation from scratch. The change in skeleton is due to the _potentiality_ that some of Manly's moves may not be compatible with her current bone. Before you all go into paranoia, this is only circumstantial. **IF**, through the course of animating some of the proposed moves cannot be done even at polished qualities, the 'unthinkable' may need to be done. If not, the better. This part is just a warning note to a probable future. Nonetheless, even if the worst case scenario will happen, giving up is no excuse. Animation is hard work and PSA is even more. 

# Conclusion

I have received from bb010g that this standardization is based solely on one person and that we should seek a consensus of at least two or more people. Again, Manly is the only one who even came up and dared to came up with a systematic approach to Lyn's gameplay mechanic. No one else at PMCC has done this, for a variety of reasons; his ideas are very concrete, mechanical, excellent guide to completion, visual and most important, solid. If we can get a standard that concretely sets out parameters that have Lyn be completed in a manner that is consistent with her style and nature, we should go for it. PM 3.6 balancing is important no doubt, but that is for later during PSA optimization, animating the mechanics is the issue here. Getting those moves to be animated. Balancing is after.

**Comment by TheSmashBoy** [comment]
Edit: Will include the jab and a few of her tilts from her prototype as a placeholder to replace her current jabs.

**Comment by bb010g** [comment]
> I have received from bb010g that this standardization is based solely on one person and that we should seek a consensus of at least two or more people. Again, Manly is the only one who even came up and dared to came up with a systematic approach to Lyn's gameplay mechanic.

If that's what's happening, just note the reasoning here before you put out a big change. GitHub issues are a lot more accessible long-term than Matrix/Discord, which is good for future reference.

> If we can get a standard that concretely sets out parameters that have Lyn be completed in a manner that is consistent with her style and nature, we should go for it. PM 3.6 balancing is important no doubt, but that is for later during PSA optimization, animating the mechanics is the issue here. Getting those moves to be animated. Balancing is after.

If we're going to possibly be taking a few steps back before she gets completed, that's fine as long as it's explicitly stated and agreed upon. I'm fine with it. We'll probably need to note it in the README at least.

**Comment by TheSmashBoy** [comment]
@bb010g Again, the discussion already took place on the Discord and the flow is going pretty well, we manage disagreements and compromise fairly well. There had to be reforms after a discussion with Manly on his inputs of his proposed attacks and some had to be tweaked or added a few more details. But it's coming along well. 

Big announcement? What is 'big' here?

**Comment by TheSmashBoy** [comment]
Closing because:

1) Ultimately no one showed up.
2) Read issue #12 .
